version: "2"
services:
   app:
      build: api
      image: epik8s/epi_2020_group6_paas:1.1
      depends_on:
          - redis
          - db
      ports:
        - 3000
      environment:
          - DB_NAME=dbtest
          - DB_HOST=db
          - DB_USER=testusr
          - DB_PORT=5432
          - DB_PASSWORD=azerazer
          - REDIS_HOST=redis
          - REDIS_PORT=6379
   redis:
      image: "redis:alpine"
      ports:
        - 6379
   db:
      image: "postgres:12"
      environment:
           - POSTGRES_PASSWORD=azerazer
           - POSTGRES_USER=testusr
           - POSTGRES_DB=dbtest
      ports:
        - 5432
      volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
   nginx:
      image: "nginx"
      depends_on:
        - app
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "3000:80"
