apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o helm --build none --volumes hostPath
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 80
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
